// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: url-shortener/shortener.proto

package shortener

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OriginURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OriginURL) Reset() {
	*x = OriginURL{}
	mi := &file_url_shortener_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OriginURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginURL) ProtoMessage() {}

func (x *OriginURL) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginURL.ProtoReflect.Descriptor instead.
func (*OriginURL) Descriptor() ([]byte, []int) {
	return file_url_shortener_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *OriginURL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortURL) Reset() {
	*x = ShortURL{}
	mi := &file_url_shortener_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURL) ProtoMessage() {}

func (x *ShortURL) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURL.ProtoReflect.Descriptor instead.
func (*ShortURL) Descriptor() ([]byte, []int) {
	return file_url_shortener_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortURL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_url_shortener_shortener_proto protoreflect.FileDescriptor

const file_url_shortener_shortener_proto_rawDesc = "" +
	"\n" +
	"\x1durl-shortener/shortener.proto\x12\tshortener\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\"'\n" +
	"\tOriginURL\x12\x1a\n" +
	"\x03url\x18\x01 \x01(\tB\b\xfaB\x05r\x03\x88\x01\x01R\x03url\"&\n" +
	"\bShortURL\x12\x1a\n" +
	"\x03url\x18\x01 \x01(\tB\b\xfaB\x05r\x03\x88\x01\x01R\x03url2\xb3\x01\n" +
	"\fUrlShortener\x12O\n" +
	"\bWrapLink\x12\x14.shortener.OriginURL\x1a\x13.shortener.ShortURL\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/generate\x12R\n" +
	"\n" +
	"UnwrapLink\x12\x13.shortener.ShortURL\x1a\x14.shortener.OriginURL\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/unwrap/{url}B\x10Z\x0e/pkg/shortenerb\x06proto3"

var (
	file_url_shortener_shortener_proto_rawDescOnce sync.Once
	file_url_shortener_shortener_proto_rawDescData []byte
)

func file_url_shortener_shortener_proto_rawDescGZIP() []byte {
	file_url_shortener_shortener_proto_rawDescOnce.Do(func() {
		file_url_shortener_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_url_shortener_shortener_proto_rawDesc), len(file_url_shortener_shortener_proto_rawDesc)))
	})
	return file_url_shortener_shortener_proto_rawDescData
}

var file_url_shortener_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_url_shortener_shortener_proto_goTypes = []any{
	(*OriginURL)(nil), // 0: shortener.OriginURL
	(*ShortURL)(nil),  // 1: shortener.ShortURL
}
var file_url_shortener_shortener_proto_depIdxs = []int32{
	0, // 0: shortener.UrlShortener.WrapLink:input_type -> shortener.OriginURL
	1, // 1: shortener.UrlShortener.UnwrapLink:input_type -> shortener.ShortURL
	1, // 2: shortener.UrlShortener.WrapLink:output_type -> shortener.ShortURL
	0, // 3: shortener.UrlShortener.UnwrapLink:output_type -> shortener.OriginURL
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_url_shortener_shortener_proto_init() }
func file_url_shortener_shortener_proto_init() {
	if File_url_shortener_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_url_shortener_shortener_proto_rawDesc), len(file_url_shortener_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_url_shortener_shortener_proto_goTypes,
		DependencyIndexes: file_url_shortener_shortener_proto_depIdxs,
		MessageInfos:      file_url_shortener_shortener_proto_msgTypes,
	}.Build()
	File_url_shortener_shortener_proto = out.File
	file_url_shortener_shortener_proto_goTypes = nil
	file_url_shortener_shortener_proto_depIdxs = nil
}
